import {
  AG_SCOUT_TAG,
  AG_VIEWER_TAG,
  CRM_TAG,
  PROJECTS_TAG,
  SELAM_HALI_MOBILE_TAG,
  SELAM_HALI_TAG,
  TAGLET_MOBILE_TAG,
  TAGLET_TAG,
  UMBRELLA_TAG,
} from ".";

export const AG_SCOUT_ROUTE = `/${PROJECTS_TAG}/${AG_SCOUT_TAG}`;
export const AG_VIEWER_ROUTE = `/${PROJECTS_TAG}/${AG_VIEWER_TAG}`;
export const CRM_ROUTE = `/${PROJECTS_TAG}/${CRM_TAG}`;
export const SELAM_HALI_ROUTE = `/${PROJECTS_TAG}/${SELAM_HALI_TAG}`;
export const SELAM_HALI_MOBILE_ROUTE = `/${PROJECTS_TAG}/${SELAM_HALI_MOBILE_TAG}`;
export const TAGLET_ROUTE = `/${PROJECTS_TAG}/${TAGLET_TAG}`;
export const TAGLET_MOBILE_ROUTE = `/${PROJECTS_TAG}/${TAGLET_MOBILE_TAG}`;
export const UMBRELLA_ROUTE = `/${PROJECTS_TAG}/${UMBRELLA_TAG}`;
